Repository all-in-competition/all-in-backend, pull requests merged in 2024-07, with the labels that each got.

#2 Fix/1
  api/configs/app_config.py
  api/cruds/member.py
  api/db.py
  api/routers/login.py
  api/schemas/task.py
  requirements.txt
Labels: :bug: fix

#7 Chore: 사용되지 않는 파일 삭제
  api/main.py
  api/models/member.py
  api/routers/done.py
  api/routers/login.py
  api/routers/post.py
  api/routers/task.py
  api/schemas/model.py
  api/schemas/task.py
Labels: 📝 chore

#9 Feat: 세션에 저장될 유저 정보 추가
  api/cruds/member.py
  api/routers/login.py
Labels: :sparkles: feat

#11 Feat: 게시글 리스트 반환값 변경
  api/cruds/post.py
  api/models/model.py
  api/schemas/post.py
Labels: :sparkles: feat

#15 Feat: 게시글 상세보기 구현
  api/cruds/post.py
  api/routers/post.py
  api/schemas/post.py
Labels: :sparkles: feat

#16 Feat: 게시글 좋아요 기능 구현
  api/cruds/post.py
  api/routers/post.py
Labels: :sparkles: feat

#17 Feat: 이력서 생성
  api/cruds/member.py
  api/cruds/resume.py
  api/routers/login.py
  api/schemas/resume.py
Labels: :bug: fix, :sparkles: feat

#20 Feat: 이력서 수정
  api/cruds/resume.py
  api/main.py
  api/routers/resume.py
Labels: :sparkles: feat

#29 Fix: 사용자-게시글 관계에서 좋아요 기능 데이터 추가 누락 수정
  api/cruds/post.py
  api/routers/post.py
  api/schemas/like.py
Labels: :bug: fix

#32 Feat: tag 생성
  api/cruds/post.py
  api/cruds/resume.py
  api/routers/resume.py
  api/schemas/resume.py
Labels: :sparkles: feat

#39 Fix 38 이력서 목록 보기 및 이력서 상세보기 오류 수정
  alembic/versions/3d25789029dc_add_resume_updated_at.py
  api/cruds/member.py
  api/cruds/post.py
  api/cruds/resume.py
  api/cruds/tag.py
  api/models/model.py
  api/routers/post.py
  api/routers/resume.py
  api/schemas/post.py
  api/schemas/resume.py
Labels: :bug: fix, :sparkles: feat

#47 Feat: 채팅방 리스트 조회 api 구현
  api/cruds/chatroom.py
  api/main.py
  api/routers/chatroom.py
  api/schemas/chatroom.py
Labels: :sparkles: feat

#51 Feat; 초대, 참가 신청 실시간 알람 구현, 신청 수락 기능 구현
  api/cruds/alarm.py
  api/routers/alarm.py
  api/routers/post.py
  api/schemas/alarm.py
Labels: :sparkles: feat

#52 Refactor: 파일명 변경 및 채팅 연결 오류 수정
  api/main.py
  api/routers/chat.py
Labels: :recycle: refactor

#55 Feat 게시글 생성시 단체 채팅방 생성 기능 구현
  api/cruds/post.py
  api/routers/alarm.py
Labels: :bug: fix, :sparkles: feat

#57 feat: 닉네임 변경 기능 구현
  api/cruds/member.py
  api/main.py
  api/routers/member.py
Labels: :sparkles: feat

#59 Feat: 개인 채팅방 생성 기능 구현
  api/cruds/chatroom.py
  api/routers/chat.py
  api/routers/chatroom.py
Labels: :sparkles: feat

#63 fix: 단체 채팅방 중복 참여 예외처리, 게시글의 현재 참여중인 인원 갱신
  api/cruds/chatroom.py
Labels: :bug: fix

#64 Refactor: 게시글 생성시 채팅방 생성하는 로직 리팩터링
  api/cruds/chatroom.py
  api/cruds/post.py
Labels: :recycle: refactor

#66 Refactor: 게시글 생성 시 요청 바디에서 user_id 제거 후 세션에서 가져오기
  api/cruds/post.py
  api/routers/post.py
  api/schemas/post.py
Labels: :recycle: refactor

#69 feat: 단체 채팅 퇴장기능 구현
  api/cruds/chatroom.py
  api/routers/chatroom.py
  api/schemas/chatroom.py
Labels: :sparkles: feat

#73 fix: crud.tag의 사용하지 않는 import 삭제
  api/cruds/tag.py
Labels: :bug: fix

#74 Feat: 좋아요 게시글 조회
  api/cruds/post.py
  api/routers/member.py
Labels: :sparkles: feat

#78 Fix 게시글 마감 기능 구현
  alembic/versions/5c4c5d749f55_change_active_to_ongoing.py
  api/cruds/post.py
  api/models/model.py
  api/routers/post.py
Labels: :bug: fix, 📝 chore

#81 Feat: 게시글 상세보기에서 작성자 id 추가
  api/cruds/post.py
  api/schemas/post.py
Labels: :sparkles: feat

#85 Fix: 세션에서 유저 ID 조회 시 누락된 경우 예외 처리
  api/routers/alarm.py
  api/routers/chatroom.py
  api/routers/member.py
  api/routers/post.py
  api/routers/resume.py
Labels: :bug: fix

#86 Fix 단체 채팅방 인원 변동시 마감 여부 변경
  api/cruds/chatroom.py
Labels: :bug: fix
